name       : ruby_dep
version    : 1.3.1
release    : 4
source     :
    - https://rubygems.org/downloads/ruby_dep-1.3.1.gem : 14814183f004eba3e3db9c9b534b65208294412ab99aa337e934a5f4bbfd186c
license    : MIT
component  : programming.ruby
summary    : RubyGem - ruby_dep
description: |
    Creates a version constraint of supported Rubies, suitable for a gemspec file.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
